version: "3"
services:
  openmrs-middleware:
    restart: always
    image: makili/openmrs-middleware:1.0.0
    container_name: openmrs-middleware
    ports: 
      - 8086:8086
    env_file: .env
    environment:
      PORT: $PORT
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_HOST: openmrs-mysql
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_USER_PASSWORD: $MYSQL_USER_PASSWORD
      KAFKA_BROKER: $KAFKA_BROKER
      KAFKA_PATIENT_TOPIC_CONSUMER_GROUP_ID: $KAFKA_PATIENT_TOPIC_CONSUMER_GROUP_ID
      KAFKA_VISIT_TOPIC_CONSUMER_GROUP_ID: $KAFKA_VISIT_TOPIC_CONSUMER_GROUP_ID
      OPENMRS_MYSQL_DATABASE: $OPENMRS_MYSQL_DATABASE
      OPENMRS_SITE: $OPENMRS_SITE
      OPENMRS_ADMIN_USERNAME: $OPENMRS_ADMIN_USERNAME
      OPENMRS_ADMIN_PASSWORD: $OPENMRS_ADMIN_PASSWORD
      OPENMRS_REST_API_ROUTE: $OPENMRS_REST_API_ROUTE
      SECRET_KEY: $SECRET_KEY
      SESSION_EXPIRATION: $SESSION_EXPIRATION
      LOG_FILE: $LOG_FILE
      TZ: $TZ
      EDI_DIR: $EDI_DIR
    depends_on: 
      - openmrs
      - openmrs-mysql
      - kafka
    volumes: 
      - ./:/usr/src/openmrs-middleware

  openmrs-mysql:
    restart: "always"
    image: mysql:5.7
    container_name: openmrs-mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-openmrs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    healthcheck:
      test: "exit 0"
    volumes:
      - openmrs-mysql-data:/var/lib/mysql

  openmrs:
    restart: "always"
    image: openmrs/openmrs-distro-platform:2.1.3
    container_name: openmrs
    depends_on:
      - openmrs-mysql
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: ${MYSQL_DB:-openmrs}
      DB_HOST: openmrs-mysql
      DB_USERNAME: ${MYSQL_USER:-openmrs}
      DB_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      MODULE_WEB_ADMIN: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - openmrs-data:/usr/local/tomcat/.OpenMRS/
      - /usr/local/tomcat/.OpenMRS/modules/
      - /usr/local/tomcat/.OpenMRS/owa/
    #TODO add the UI modules
 
  zookeeper:
    restart: "always"
    image: zookeeper:3.6.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181

  kafka:
    restart: "always"
    image: wurstmeister/kafka:2.11-2.0.1
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  openmrs-mysql-data:
  openmrs-data:
     