version: "3"
services:
  openmrs-middleware:
    image: makili/openmrs-middleware:1.0.0
    container_name: openmrs-middleware
    ports: 
      - 8086:8086
    environment:
      PORT: 8086
      MYSQL_PORT: 3306
      MYSQL_HOST: 
      MYSQL_USERNAME: smartcerv
      MYSQL_USER_PASSWORD: smartcerv
      KAFKA_BROKER: kafka:9092
      KAFKA_PATIENT_TOPIC_CONSUMER_GROUP_ID: openmrs-patient
      KAFKA_VISIT_TOPIC_CONSUMER_GROUP_ID: openmrs-visit
      OPENMRS_MYSQL_DATABASE: openmrs
      OPENMRS_SITE: http://openmrs:8080/openmrs/
      OPENMRS_ADMIN_USERNAME: admin
      OPENMRS_ADMIN_PASSWORD: Openmrs4Bluecode
      OPENMRS_REST_API_ROUTE: ws/rest/v1/
      SECRET_KEY: EyxPxKlBREO49w4KlW7Y05g4giF00IHujOaOYX
      SESSION_EXPIRATION: 50000000
      LOG_FILE: ./logs
      TZ: 'Africa/Harare'
      EDI_DIR: ./EDI
    depends_on: 
      - openmrs
      - openmrs-mysql
      - kafka
    volumes: 
      - ./:/src/openmrs-middleware

  openmrs-mysql:
    restart: "always"
    image: mysql:5.7
    container_name: openmrs-mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-openmrs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    healthcheck:
      test: "exit 0"
    volumes:
      - openmrs-mysql-data:/var/lib/mysql

  openmrs:
    restart: "always"
    image: openmrs/openmrs-distro-platform:2.1.3
    container_name: openmrs
    depends_on:
      - openmrs-mysql
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: ${MYSQL_DB:-openmrs}
      DB_HOST: openmrs-mysql
      DB_USERNAME: ${MYSQL_USER:-openmrs}
      DB_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      MODULE_WEB_ADMIN: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - openmrs-data:/usr/local/tomcat/.OpenMRS/
      - /usr/local/tomcat/.OpenMRS/modules/
      - /usr/local/tomcat/.OpenMRS/owa/
    #TODO add the UI modules
 
  zookeeper:
    image: zookeeper:3.6.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-2.0.1
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  openmrs-mysql-data:
  openmrs-data:
     