import controllerGenerator from './controllerGenerator';
import daoGenerator from "../dao/daoGenerator";
import dbConnection from '../resources/dbConnection';

let connection = dbConnection.promise();

const CONTROLLERS = [

    controllerGenerator('location')(daoGenerator('location','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('location/tag')(daoGenerator('location_tag','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('location/tag/map')(daoGenerator('location_tag_map',null,null,connection)),
    controllerGenerator('location/attribute')(daoGenerator('location_attribute','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('location/attribute/type')(daoGenerator('location_attribute_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('person/name')(daoGenerator('person_name','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('person/address')(daoGenerator('person_address','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('person')(daoGenerator('person','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('patient')(daoGenerator('patient','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('patient/identifier')(daoGenerator('patient_identifier','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('patient/identifier/type')(daoGenerator('patient_identifier_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('obs')(daoGenerator('obs','uuid',['date_created'],connection)),
    controllerGenerator('concept')(daoGenerator('concept','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/answer')(daoGenerator('concept_answer','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/attribute')(daoGenerator('concept_attribute','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/attribute/type')(daoGenerator('concept_attribute_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/class')(daoGenerator('concept_class','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/complex')(daoGenerator('concept_complex','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/datatype')(daoGenerator('concept_datatype','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/description')(daoGenerator('concept_description','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/map/type')(daoGenerator('concept_map_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/name')(daoGenerator('concept_name','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/name/tag')(daoGenerator('concept_name_tag','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/name/tag/map')(daoGenerator('concept_name_tag_map','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/numeric')(daoGenerator('concept_numeric','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/proposal')(daoGenerator('concept_proposal','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/proposal/tag/map')(daoGenerator('concept_proposal_map','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/reference/map')(daoGenerator('concept_reference_map','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/reference/source')(daoGenerator('concept_reference_source','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/reference/term')(daoGenerator('concept_reference_term','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/reference/term/map')(daoGenerator('concept_reference_term_map','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/set')(daoGenerator('concept_set','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/state/conversion')(daoGenerator('concept_state_conversion','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('concept/stop/word')(daoGenerator('concept_stop_word','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('conditions')(daoGenerator('conditions','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('encounter')(daoGenerator('encounter','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('encounter/provider')(daoGenerator('encounter_provider','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('encounter/role')(daoGenerator('encounter_role','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('encounter/type')(daoGenerator('encounter_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('field')(daoGenerator('field','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('field/answer')(daoGenerator('field_answer','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('field/type')(daoGenerator('field_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('user')(daoGenerator('users','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('provider')(daoGenerator('provider','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('visit/type')(daoGenerator('visit_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('allergy')(daoGenerator('allergy','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('allergy/reaction')(daoGenerator('allergy_reaction','uuid',null,connection)),
    controllerGenerator('note')(daoGenerator('note','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('drug')(daoGenerator('drug','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('drug/order')(daoGenerator('drug_order','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('drug/ingredient')(daoGenerator('drug_ingredient','uuid',null,connection)),
    controllerGenerator('orders')(daoGenerator('orders','uuid',['date_created'],connection)),
    controllerGenerator('order/frequency')(daoGenerator('order_frequency','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('order/type')(daoGenerator('order_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('order/type/class/map')(daoGenerator('order_type_class_map',null,null,connection)),
    controllerGenerator('notification/alert')(daoGenerator('notification_alert','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('notification/alert/recipient')(daoGenerator('drug','uuid',null,connection)),
    controllerGenerator('person/merge/log')(daoGenerator('person_merge_log','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('appointmentscheduling/appointment')(daoGenerator('appointmentscheduling_appointment','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('appointmentscheduling/appointment/block')(daoGenerator('appointmentscheduling_appointment_block','uuid',['date_created'],connection)),
    controllerGenerator('appointmentscheduling/appointment/request')(daoGenerator('appointmentscheduling_appointment_request','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('appointmentscheduling/appointment/status/history')(daoGenerator('appointmentscheduling_appointment_status_history',null,null,connection)),
    controllerGenerator('appointmentscheduling/appointment/type')(daoGenerator('appointmentscheduling_appointment_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('appointmentscheduling/block/type/map')(daoGenerator('appointmentscheduling_block_type_map',null,null,connection)),
    controllerGenerator('appointmentscheduling/time/slot')(daoGenerator('appointmentscheduling_time_slot','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('privilege')(daoGenerator('privilege','uuid',null,connection)),
    controllerGenerator('relationship')(daoGenerator('relationship','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('relationship/type')(daoGenerator('relationship_type','uuid',['date_created','date_changed'],connection)),
    controllerGenerator('role')(daoGenerator('role','uuid',null,connection)),
    controllerGenerator('role/privilege')(daoGenerator('role_privilege',null,null,connection)),
    controllerGenerator('role/role')(daoGenerator('role_role',null,null,connection)),
    controllerGenerator('user/role')(daoGenerator('user_role',null,null,connection)),
    controllerGenerator('user/property')(daoGenerator('user_property',null,null,connection))
];

export {CONTROLLERS}
